/* 
* Class: CMSC203 
* Instructor: Ahmed Tarek
* Description: A game program where the user is told to guess the random number generated by the program until they get it right
* Due: 2/22/2021
* Platform/compiler: Eclipse
* I pledge that I have completed the programming assignment independently.
I have not copied the code from a student or any source.
I have not given my code to any student.
Print your Name here: Nicholas Prakoso
*/

import java.util.Scanner;
import java.util.Random;

public class RandomNumberGuesser extends RNG {

	public static void main(String[] args) {
		String tryAgain;
		//Code is put into a do/while loop so that program repeats when user wants to play again at the end
		do {
			int randNum = RNG.rand();
			int nextGuess;
			int highGuess = 100;
			int lowGuess = 0;
			int count = 0;
			RNG.rand();
		
			Scanner userInput = new Scanner(System.in);
		
			System.out.println("Enter your first guess: ");
			nextGuess = userInput.nextInt();
			RNG.getCount();
			count++;
			System.out.println("Number of guesses is " + count);
			count++;
			/*Upon entering a guess, the program prints out a message telling them whether their guess was too high
			 * or too low depending on what they guessed in relation to the random number generated
			 */
			if (nextGuess > randNum) {
				System.out.println("Your guess is too high");
				highGuess = nextGuess;
			} else if (nextGuess < randNum) {
				System.out.println("Your guess is too low");
				lowGuess = nextGuess;
			}
			//Statements repeat in while loop as long as the user doesn't guess the random number correctly
			while (nextGuess != randNum) {
				System.out.println("Enter your next guess between " + lowGuess + " and " + highGuess);
				nextGuess = userInput.nextInt();
				System.out.println("Number of guesses is " + count);
				RNG.inputValidation(nextGuess, lowGuess, highGuess);
				if (nextGuess > randNum && nextGuess < highGuess) {
					System.out.println("Your guess is too high");
					highGuess = nextGuess;
				} else if (nextGuess < randNum && nextGuess > lowGuess) {
					System.out.println("Your guess is too low");
					lowGuess = nextGuess;
				}
				count++;
				RNG.getCount();
			}
		
			Scanner tryAgainInput = new Scanner(System.in);
		
			System.out.println("Congratulations, you guessed correctly");
			System.out.println("Try again? (yes or no)");
			tryAgain = tryAgainInput.nextLine();
		
			if (tryAgain.equals("yes")) {
				RNG.resetCount();
			} else if (tryAgain.equals("no")) {
				System.out.println("Thanks for playing...");
			}
		} while (tryAgain.equals("yes"));
		System.exit(0);
		
	}

}
